# 실행할 컨테이너
services:   # 서비스들을 정의
  app1: #이름
    ports:  #포트
      - 8000:80
    build:  # 빌드 설정
      context: ./app1
  app2:
    ports:
      - 9000:80
    build:
      context: ./app2
  lb:
    ports:
      - 80:80
    build:
      context: ./lb
